/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaPractice;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        square seq1 = new square("sequar1", 10);
        shape seq2 = new square("seq2", 5);

        circle circle1 = new circle("c1", 2);
        circle circle2 = new circle("c2", 3);

        System.out.println(seq1.area());
        System.out.println("please input the nme os circle :");
        Scanner circleInputName = new Scanner(System.in);
        String name = circleInputName.nextLine();

        System.out.println("please input the radius  os circle :");
        Scanner circleInput = new Scanner(System.in);
        int raduies = circleInput.nextInt();

        if (raduies < 0) {
            throw new ArithmeticException("ERROR RADUIES ");
        }

        System.out.println("name is " + name);

        System.out.println("kiddies is " + raduies);


        System.out.println("area is " + circle.area(raduies));


    }
}
