/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaPractice;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

     square seq1=new square("sequar1",10);
     shape seq2=new square("seq2",5);

     circle circle1=new circle("c1",2);
     circle circle2=new circle("c2",3);

     System.out.println(seq1.area());


    }
}
